name: Run Python Tests and flake 8
on:
  pull_request:
    branches:
      - pruebas

jobs: 
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .

      - name: Run tests with pytest
        run: pytest